project:
  type: website

website:
  title: "Bioconductor Translations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - faq.qmd
      - news.qmd
      - about.qmd
      - translate.qmd
      - status.qmd
      - contributors.qmd

format:
  html:
    theme: yeti
